### ISSUE TITLE
Outdated version, not displaying upstream version

### ISSUE THREAD

**Issue by shundhammer** [area-of-dev/QDirStat.AppImage#1]
This AppImage is way outdated, yet it suggests to be up to date.

And it doesn't even **show** what version of QDirStat is being packaged.

I summarized the main concerns with this here:

https://github.com/shundhammer/qdirstat/issues/168

**Comment by AlexWoroschilow** [comment]
This is a latest version available in the official ubuntu repository. And since there is no way to get the version of the package using cli (like --version or -version), it will stay as is. 
![image](https://user-images.githubusercontent.com/3255923/166324251-52ffd403-a37c-4d78-8e81-af3d374d5ebe.png)


update: added comments here https://apprepo.de/appimage/qdirstat

**Comment by AlexWoroschilow** [comment]
@shundhammer qDirStat is such a gorgeous programm. It would be very nice if you change your mind and provide the official up to date AppImage from the Author. :pray:

**Comment by shundhammer** [comment]
So, not only are you not building QDirStat from source, you are just repacking it from .deb format into AppImage format; you also don't know how to query a .deb package that you have in front of you for its version? Seriously?

**Comment by AlexWoroschilow** [comment]
If this is an answer to the question why there is no option to get the version of the software using the well known and commonly used argument like "--version" ok, i get it.

**Comment by shundhammer** [comment]
The problem is that you shouldn't even _need_ to query QDirStat for its version.

- If you build it from source, there is the [Version.h](https://github.com/shundhammer/qdirstat/blob/master/src/Version.h) header file that answers the question.

- If you are a human user, the question is answered in the _About QDirStat_ dialog in the _Help_ menu.

- If you are dealing with a pre-built package (.deb in this case), the version number is in the file name, and there are also various ways to get that information with the associated package manager command (`dpkg`, `dpkg-deb`).

I don't know the normal procedure how an AppImage is built, but I would think that it involves _building_ the binary, not just extracting one from another package format and repackaging it. That also explains why it depends on such specific versions of _glibc_ which IMHO very much violates the whole idea behind a format like AppImage and its basic premise that it should run _everywhere_. It's pointless to just repackage a .deb package so it only runs on that same distro or a newer one; that only consumes tons of disk space for no gain whatsoever. That can easily be achieved by simply using that original .deb package.I have a hard time to figure out what problem that might solve.

**Comment by AlexWoroschilow** [comment]
> I don't know the normal procedure how an AppImage is built, but I would think that it involves _building_ the binary, not just extracting one from another package format and repackaging it.

I strongly disagree. Let me explain. 
Fist of all, the target of the apprepo projects never was to build the latest up to date AppImages from the source code(!).  I see it as a task for the developers of the software, at least if they care about their users. The apprepo is a proof of the concept of the dependency-less package managing in the linux world. That is the point. 

Now taking that under the consideration, the task was to get as many working high-quality AppImages as possible in a short period of time. I have build a software which builds the AppImages automatically from the ubuntu and centos repositories using the python interfaces to the apt and dnf.  With this soft I was able to package already about 300 different pieces of the software as an AppImage written in java, c, c++, perl, python, mono  and so on in my free time as a hobby project in just a few weeks. It would have taken much more time building it all from the source code, and i am sure it is possible, but that is not fun and i don't want to do it. 

A you see, the latest up to date AppImage of the QDirStat was never a target, it is collateral. But if you will change your mind and build one, a lot of people will be thankful including me. 

> That also explains why it depends on such specific versions of _glibc_ which IMHO very much violates the whole idea behind a format like AppImage and its basic premise that it should run _everywhere_.

From my point of view, it will never work everywhere. But some wide subset of the stable linux distributions is good enough for me. 

> It's pointless to just repackage a .deb package so it only runs on that same distro or a newer one; that only consumes tons of disk space for no gain whatsoever. That can easily be achieved by simply using that original .deb package.I have a hard time to figure out what problem that might solve.

Sure there are a lot of ways how to run the software on linux host. In this case the dependency is the key. I would love to keep my systems stable an clean having all the third-party software as a single file without any dependencies. Even with a price of a few MB extra space.

**Comment by shundhammer** [comment]
> > I don't know the normal procedure how an AppImage is built, but I would think that it involves _building_ the binary, not just extracting one from another package format and repackaging it.
> 
> I strongly disagree. Let me explain. Fist of all, the target of the apprepo projects never was to build the latest up to date AppImages from the source code(!).

I am not talking about building the latest Git master, but the latest _released_ version; because those released versions contain the latest bug fixes, even if you don't care about new features.

In your case, you are distributing a vastly outdated QDirStat 1.6.1 from February 2020 which is (at the time of this writing) two and a half years old, missing versions 1.7, 1.7.1, 1.8; where even the latest version 1.8 is about one year old and will be replaced by a new release soon.

https://github.com/shundhammer/qdirstat/releases

Yet you are doing daily or weekly builds ("updated at:" with a date just a few days ago) which raise the expectation among users that they'll get the most recent thing, and there is *nothing* on the AppRepo page to indicate that it's not.  A Googe search for "QDirStat updated within this week" always returns that AppRepo QDirStat page because it's auto-refreshed daily, even though it keeps rebuilding the same ancient version.

>  I see it as a task for the developers of the software,

No. Not only no, but _**hell, no**_! The author delivers the source code.  That's the "source" part of _Open Source_. 

It's the task of the distro maintainers to build it for those users (the vast majority) who can't build it themselves. I am **not** going to do the shitty work for every distribution out there (with all their quirks and oddities) on top of that. Those who feel the need to create yet another Linux distribution are responsible for that.

And frankly, the distro maintainers are generally doing a good job at that, and in a very responsible way. As long as new package formats that reinvent the wheel don't interfere with that build and delivery process, that is.

> at least if they care about their users. The apprepo is a proof of the concept of the dependency-less package managing in the linux world. That is the point.

Then you missed that point. Because _it's not dependency-less_, as your requirements with at least Ubuntu 20.04 and at least the glibc version of that distro release clearly prove. The promise of AppImage (or other similar formats like FlatPak or Snap) is just too bold a claim. It doesn't work.

> Now taking that under the consideration, the task was to get as many working high-quality AppImages as possible in a short period of time. 

Whatever noble cause it was, did it really succeed? Did it deliver upon the promise of getting rid of those pesky dependency problems? Or did it just move them to another level? A level where no _askubuntu.com_ or similar site can help them?

>I have build a software which builds the AppImages automatically from the ubuntu and centos repositories using the python interfaces to the apt and dnf. With this soft I was able to package already about 300 different pieces of the software as an AppImage written in java, c, c++, perl, python, mono and so on in my free time as a hobby project in just a few weeks. It would have taken much more time building it all from the source code, and i am sure it is possible, but that is not fun and i don't want to do it.

I can understand that, and I know about the amount of work of packaging Open Source software properly. I have been in that business since 1999. But there is a reason why companies like SUSE, Canonical and Red Hat employ so many (100+? 200+?) software engineers just for packaging all that Open Source software. It's not something that can easily be done as a side job; at least not when QA / testing and security are taken seriously.

> A you see, the latest up to date AppImage of the QDirStat was never a target, it is collateral. But if you will change your mind and build one, a lot of people will be thankful including me.

I repeat: I will not start distributing any AppImages, FlatPaks, Snaps or whatever; for the reasons that I explained in that other issue in the QDirStat GitHub repo and its issue tracker.


> From my point of view, it will never work everywhere.

So this is a point that we both agree upon. But that's my major point of criticism on all those package formats, be it AppImage, FlatPak or Snap: They make a bold promise, and they know very well that they can't keep it. All that those formats do is to shift the problem around a bit, but they don't solve it. And I am not even talking about different hardware architectures like ARM, PPC or whatever; it doesn't even work just limited to x64_64.

> But some wide subset of the stable linux distributions is good enough for me.

But they all do provide those library packages that applications depend upon. They have the infrastructure in place. Yes, there are pathological cases, but QDirStat in particular was designed with minimal dependencies; just the Qt and X11 libs, zlib and Glibc. It doesn't get much more basic than that.

Yet bundling them with every application, too in an AppImage makes it necessary to rebuild those AppImages basically on a daily basis because some of them will receive security or urgent bug fixes every few days, and it would be irresponsible to hold those fixes back. That of course means that a user also has to _download_ an updated AppImage every day that he wants to use the bundled application; and that along with disk space is my greatest criticism on all those package formats.

It's bad enough to be forced to download an updated web browser every 3 days. But I really don't want to download a similarly fat package every time I want to use any other application, too. And that is the downfall of all those package formats.

> > It's pointless to just repackage a .deb package so it only runs on that same distro or a newer one; that only consumes tons of disk space for no gain whatsoever. That can easily be achieved by simply using that original .deb package.I have a hard time to figure out what problem that might solve.
> 
> Sure there are a lot of ways how to run the software on linux host. In this case the dependency is the key. I would love to keep my systems stable an clean having all the third-party software as a single file without any dependencies. Even with a price of a few MB extra space.

It's not just "a few MB". It _multiplies_ the overall disk size requirements, and, worse, it multiplies the required _download_ sizes; basically every day that you want to start the packages program. See above. This turns a simple program start into a painfully tedious process. I don't know about your Internet connection, but I really don't want to wait for a 600+ MiB download every time I start any nontrivial program.

If users still wish to do that, it's their choice. But please be honest with them and tell them what they are going to get; right now they get the impression that they will receive the latest QDirStat which simply isn't true.

When I read "Updated at:" <yesterday's date>, I feel confident that I will get something _new_; certainly not something from two and a half years ago. Much less do i want to download the same two and a half years old thing every 3 days just because somebody fixed a Korean input method in libxcb which happens to be part of the AppImage, or because some Pacific island nation decided to switch to a time zone closer to China.

**Comment by AlexWoroschilow** [comment]
Thank you for your opinion which i am already familiar with from the discussion with the inventor of the AppImage in the QDirStat repo. I see your point, but i still disagree with almost everything you was talking about. All problems mentioned above are easy to solve with the resources way less than 100+ or 200+ maintainers. Thouse ressources might have been invested into improving of the wayland / pipewire / libinput etc.. instead of doing the same boring stuff over and over again for every distro in the world. 


> > I see it as a task for the developers of the software,
> 
> No. Not only no, but _**hell, no**_! The author delivers the source code. That's the "source" part of _Open Source_.
You are talking about the really rare special case. I am glad it works for you so well since 1999. But take a look at the mobile world, at the desktop world. The author of the software delivers the ready to use software, the source code is optional. 
> I am **not** going to do the shitty work for every distribution out there (with all their quirks and oddities) on top of that. Those who feel the need to create yet another Linux distribution are responsible for that.
That's the point, this is really boring, nobody wants to do it, and exactly this problem the AppImage tries to solve. It might be not perfect yet, but it goes the right direction (IMHO). 

Regarding the matter, since there is no automated way to get the version number of the software with every build, the best i can do is to put the info how to get this information using the approach mentioned here:
> * If you are a human user, the question is answered in the _About QDirStat_ dialog in the _Help_ menu.

p.s. Because of your very strong and rigid opinion combined with the focusing on the criticism without any constructive suggestions sometimes enforced with few ridiculous reasonless assumptions i prefer to close this discussion at this point.
